name: Deploy Next.js static export to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Отключаем серверные и динамические страницы только на CI
      - name: Disable server-only & dynamic pages for static export
        shell: bash
        run: |
          if [ -d "./app/api" ]; then mv ./app/api ./app/__api_disabled; fi
          if [ -d "./pbn-service" ]; then mv ./pbn-service ./__pbn_disabled; fi
          if [ -d "./app/shop/[slug]" ]; then mkdir -p ./app/__disabled_shop; mv "./app/shop/[slug]" "./app/__disabled_shop/slug"; fi
          if [ -d "./app/checkout" ]; then mv ./app/checkout ./app/__disabled_checkout; fi
          if [ -d "./app/cart" ]; then mv ./app/cart ./app/__disabled_cart; fi
          if [ -d "./app/upload" ]; then mv ./app/upload ./app/__disabled_upload; fi
          if [ -d "./app/verify" ]; then mv ./app/verify ./app/__disabled_verify; fi
          if [ -d "./app/register" ]; then mv ./app/register ./app/__disabled_register; fi
          if [ -d "./app/reviews" ]; then mv ./app/reviews ./app/__disabled_reviews; fi
          if [ -d "./app/auth" ]; then mv ./app/auth ./app/__disabled_auth; fi

      - name: Install dependencies
        run: npm ci

      - name: Build (output: export already writes to ./out)
        env:
          NEXT_STATIC_EXPORT: "1"
        run: npm run build

      - name: Upload artifact (./out)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
